observIQ/application-helm-charts

- charts/clickhouse/Chart.yaml
- charts/clickhouse/templates/promtail-config.yaml
Added multiline error logs so all stack trace gets grouped together. Also changes __path__ to be same as the [agent.jsonnet](https://github.com/observIQ/cloud-onboarding/pull/20/files#diff-68058b0f23db42b1d15cb51ef8fd127a06ce86764a12c75f6239b340d6137239R23)
Before:
After:
> clickhouse: add multiline to promtail logging

- README.md
- container/wildfly/standalone.xml
The container was initially configured to accept connections only from `127.0.0.1`. When forwarding the appropriate port for the container, we could hit the metrics endpoint, but a pod running within the cluster wouldn't be able to scrape that endpoint.
* updated bind addresses to `0.0.0.0`
> Updated wildfly container bind addresses

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
* Added an available [prometheus exporter](https://github.com/criteo/cassandra_exporter) to the deployment
* set `CASSANDRA_DC`
* set `CASSANDRA_CLUSTER_NAME`
* updated `JVM_OPTS`
* set `MAX_HEAP_SIZE`
* set `HEAP_NEWSIZE`
* set `CASSANDRA_LISTEN_ADDRESS`
> Add Prometheus exporter to Cassandra chart

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
- charts/cassandra/values.yaml
* added readiness probe
* added script for readiness probe from [example](https://kubernetes.io/docs/tutorials/stateful-application/cassandra/#using-a-statefulset-to-create-a-cassandra-ring)
* bumped chart version to `0.0.5`
> Chart Update: Cassandra

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
- charts/cassandra/values.yaml
These were asks of Grafana, porting them here so that in future vendors of the chart the changes will not get lost.
[cassandra-stress](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwilso36lev9AhWxFlkFHTcRAroQFnoECA8QAQ&url=https%3A%2F%2Fcassandra.apache.org%2Fdoc%2Flatest%2Fcassandra%2Ftools%2Fcassandra_stress.html&usg=AOvVaw0ySe67fpnNvnmTB-k6wm2i) is the tool being used here and requires connection with port 9042. We target the service endpoint in order to let that do the load balancing.
The cronjob will run periodically in 5 minute stints we are both reading and writing data to the pods. 
As far as renames I think container should be the only thing left named `cassandra` but we wanted to make sure to use `apache-cassandra` whenever possible.
> Add loadgen and make cassandra -> apache cassandra

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
Some users who don't have enough resources to consistently run with 100000 iterations cause the cronjob to always fail. Generically we just want to generate some reads/writes so we think lowering this to 100 makes sense. 
```
Failed to create client too many times
Failed to create client too many times
Failed to create client too many times
Failed to create client too many times
java.lang.RuntimeException: Failed to execute warmup
at org.apache.cassandra.stress.StressAction.warmup(StressAction.java:128)
at org.apache.cassandra.stress.StressAction.run(StressAction.java:71)
at org.apache.cassandra.stress.Stress.run(Stress.java:101)
at org.apache.cassandra.stress.Stress.main(Stress.java:54)
command terminated with exit code 1
```
> Lower cassandra-stress loadgen to be 100

- .github/workflows/container.yaml
This should allow us to use the single "build and push" job and exclude combinations we don't want built/pushed for containers we create.
* Updated container CI to use a matrix for different architectures 
* excluded the combination of mesos and amd64
> Added matrix for architectures to CI

- .github/workflows/container.yaml
There are issues w/ pulling the image being built for `arm64` when it's built here, but when it was built on my machine and pushed to `bmedora/apache-mesos-1.11:0.0.3` that was able to be pulled down, regardless of the architecture.
> Removing exclusion for building Mesos (amd64)

- charts/apache-mesos/Chart.yaml
- charts/apache-mesos/templates/configmap.yaml
- charts/apache-mesos/values.yaml
[updated the startup script to include logs from the mesos agent](https://github.com/observIQ/charts/commit/fa445f04142932faf2b0c0f6cef97abb9c7f6ce0)
[bumped chart version](https://github.com/observIQ/charts/commit/a6fa57191fd0197475c7147476ef740245d3fd7b)
[updated the values yaml to use new image](https://github.com/observIQ/charts/commit/f2614035a1ca1e019e5d62cb679a0fd025b45fbe)
* New image supports both arm64/amd64
> Updated Mesos configmap and image

- .github/workflows/container.yaml
* reverted container workflow to where a single job is run per application
This should resolve the issue we are having where, while containers will build successfully, the separate architectures being built on separate jobs would get tagged differently, which is not what we want.
> Container workflow fix

- charts/apache-mesos/Chart.yaml
- charts/apache-mesos/values.yaml
* updated mesos values to point to correct image
* bumped chart version
With the change/fix for CI, the only charts that need to be updated are the ones that were pointed to the broken/messed up container release.
> Updated image being used in Mesos chart

- charts/couchbase-community/Chart.yaml
- charts/couchbase-community/README.md
> Note: Also updated some documentation, I think it makes sense to include these changes here to avoid another version bump
**Changes**
* [bumping chart version to fix releases](https://github.com/observIQ/charts/pull/47/commits/e2fce6295b33383244e10c36e6088a30f25196a0)
* [removed container configuration instructions, added note on resources](https://github.com/observIQ/charts/pull/47/commits/859ba9e2f717c8c67083dfe77e33cd53aa2b2b1e)
**Details**
In [this PR](https://github.com/observIQ/charts/pull/45) for updating Couchbase instructions in a README, we opted to not bump the chart version, as we thought it wouldn't matter for this case. We expected the release action to fail there, I believe. 
However, in a [future PR release action](https://github.com/observIQ/charts/actions/runs/533467771 …
> Fix chart release workflow

- charts/apache-hadoop/Chart.yaml
- charts/apache-hadoop/templates/hdfs-dn-svc.yaml
- charts/apache-hadoop/templates/hdfs-nn-svc.yaml
- charts/apache-hadoop/templates/yarn-nm-svc.yaml
- charts/apache-hadoop/templates/yarn-rm-svc.yaml
**Changes**
* [Updated each service to include the port for the exporter that was added](https://github.com/observIQ/charts/commit/dfb9fd342c6197050fdb91e5f629ef925d50b1df)
* [bumped chart version](https://github.com/observIQ/charts/pull/48/commits/b9dfbfb5a28ecc2f76c83f820ebc992bd80449f2)
**Details**
We have to add the exporter port to the service so that we can run this within the `k3d` environment as a sample application. We have to be able to have the `scrape_config` for this target the exporters that exist.
> Added ports to Hadoop services

- .github/workflows/ci.yaml
- .github/workflows/container.yaml
- charts/varnish/Chart.yaml
- charts/varnish/templates/deployment.yaml
- charts/varnish/values.yaml
- container/varnish-exporter/Dockerfile
**Changes**
[added Dockerfile to build varnish exporter for 6.0.11 because it is stable](https://github.com/observIQ/charts/commit/9a5d822ce66be0866c435b8faca1db67162dcd74) 
[added chart to deploy varnish and an exporter](https://github.com/observIQ/charts/commit/fd10ece808e0644b2c76811eacb6a52869eeebb3)
> Add chart and container for Varnish

- .github/workflows/container.yaml
- charts/varnish/Chart.yaml
**Changes**
* [fixed typo for varnish in the app matrix](https://github.com/observIQ/charts/commit/6b36a565d40e0a2f702c4bc551cc3a80ac330a21)
* [updated the Chart.yaml file](https://github.com/observIQ/charts/pull/50/commits/62d5bbd2e328d312f9523ae56ee6fa6ae5f7e78e)
**Details**
These changes should resolve issues with the Github workflows that failed to run.
> Fixed typo in the container CI workflow for Varnish

- charts/varnish/Chart.yaml
- charts/varnish/templates/deployment.yaml
- charts/varnish/values.yaml
**Changes**
* [updated images to be pulled from values.yaml file, specified the amd6…](https://github.com/observIQ/charts/commit/7c5821967e9dfcfda5dc3ac85bb1e300a0df30ca) 
* [bumped chart version](https://github.com/observIQ/charts/commit/185ef41c58a6037b10924cbd84477a40acb75fb6)
**Details**
Updates the chart to utilize the `values.yaml` file for specifying the number of replicas and images to be used for the app/exporter. Defaulted the exporter image to be the `amd64` container.
> Updated Varnish `values.yaml` to include images.

- charts/varnish/Chart.yaml
- charts/varnish/templates/service.yaml
**Changes**
* [added service to target the exporter pod](https://github.com/observIQ/charts/commit/84bdb59094de6fee69e2d245258a0ca579a4dd48)
* [bumped chart version](https://github.com/observIQ/charts/pull/52/commits/5ed61469e4ddc8e2c1333ca8d95e9338c6fa5a01)
**Details**
This will allow us to specifically target the exporter that's running in the deployment to scrape metrics and pull them into the local `k3d` environment.
> Added service to Varnish chart

- charts/varnish/Chart.yaml
- charts/varnish/templates/deployment.yaml
**Changes**
* [removed specifying which namespace the deployment is deployed to](https://github.com/observIQ/charts/commit/f52a9b29d0a3038403ee476757089e0c95ebc809)
* [bumped chart version](https://github.com/observIQ/charts/commit/c4afa038196246cb1a0b4b038da30298b75be9f1)
**Details**
Have to remove where we specify what namespace the deployment is applied to so that the sample application in `k3d` gets deployed properly.
> Updated Varnish deployment metadata

- charts/couchbase-community/Chart.yaml
- charts/couchbase-community/values.yaml
**Changes**
* [updated image being used to the one built/released in the repo](https://github.com/observIQ/charts/commit/db00f3707ded0a60fb024eabf832d1ad7ccb3db1)
* [bumped chart version](https://github.com/observIQ/charts/commit/1a60fc4a753dbb5e9bad0125f1dcd8bb9d775b9a)
**Details**
Updated the image in `values.yaml` to point to the released images that are built with CI/CD. Bumped the chart version.
> Updated Couchbase `values.yaml` image

- charts/varnish/Chart.yaml
- charts/varnish/templates/configmaps.yaml
- charts/varnish/templates/service.yaml
* [added nginx port to varnish service](https://github.com/observIQ/charts/commit/fa33206d9c7b1b4bfcaff7e007466ebcfc737318)
* [updated varnish config with health probe](https://github.com/observIQ/charts/commit/ec286c3447b0afdc22770d2b028c9b03d9c77897)
* [bumped chart version to 0.0.6](https://github.com/observIQ/charts/commit/a0fc7c82251ab9e00f67195570e9a45c7e9184b2)
These changes are to help with load generation against Varnish for the sample application. The port for NGINX has been added to the service, so that the load generator can send NGINX requests. 
The configuration for varnish has been updated, without a health probe, the backend metric for `varnish_backend_up` and `varnish_backend_happy` report zero values. The chart version has been bumped accordingly.
> Added health probe to Varnish deployment

- charts/varnish/templates/service.yaml
* [updated service port to be 80 where varnish is listening](https://github.com/observIQ/charts/commit/c497d72fe10fc72f26f57bf029486ef491d402e1)
I mistakenly exposed NGINX directly through the service, rather than exposing Varnish and using it as a reverse proxy, as intended. This will resolve that issue.
> Updated Varnish service port

- charts/varnish/Chart.yaml
* [updated varnish chart to 0.0.7](https://github.com/observIQ/charts/commit/65a8150c791a7aadb0d9f75f647e3ef892c1e4be)
I forgot to do this in the previous PR for varnish that we merged [here](https://github.com/observIQ/charts/pull/57).
> Varnish Chart: Bump version to 0.0.7

- charts/aerospike/Chart.yaml
- charts/aerospike/templates/configmaps.yaml
- charts/aerospike/templates/loadgen.yaml
- charts/aerospike/templates/service.yaml
- charts/aerospike/templates/statefulset.yaml
- container/aerospike-benchmark/Dockerfile
* [started aerospike helm chart](https://github.com/observIQ/charts/commit/48669e66ff98a06a412990ed3c58c365fac8753c)
* [added container with aerospike benchmark go binary installed](https://github.com/observIQ/charts/commit/479c028770ebc684a363e84de2bea1100a3b5034)
* [added aerospike.conf as configmap, added loadgen to aerospike chart](https://github.com/observIQ/charts/commit/b8a884c9ef818261c6cd418d118fdab9ac375a7a)
This chart deploys an Aerospike cluster with 3 nodes, version `6.3.0.5` of **Aerospike CE** with some load generation from an aerospike benchmark tool.
> Added Aerospike CE cluster chart

- .github/workflows/ci.yaml
- .github/workflows/container.yaml
- charts/aerospike/templates/loadgen.yaml
- charts/aerospike/templates/statefulset.yaml
- charts/aerospike/values.yaml
* [added aerospike container and chart to ci workflows](https://github.com/observIQ/charts/commit/63239851b7df5af261966210f50a91baf5374cde)
* [updated values yaml for aerospike](https://github.com/observIQ/charts/commit/a22b281bfc4f252b2bc0b0b254d2ab60f3530ed8)
Updated CI workflows to include the aerospike chart and container, updated the `values.yaml` to allow setting images for the aerospike server, the exporter, and the load generator containers.
> CI add Aerospike to container and chart releases

- charts/aerospike/Chart.yaml
* [bumping chart version to 0.0.2](https://github.com/observIQ/charts/commit/d70fd83f5e4ce697a66e72dd713135a48073f337)
Forgot this step in this [PR](https://github.com/observIQ/charts/pull/60)
> Aerospike bump chart version to 0.0.2

- charts/aerospike/Chart.yaml
- charts/aerospike/values.yaml
* [updated benchmark image to point to the image built by ci](https://github.com/observIQ/charts/commit/02baa616bf5c469341eb2fe0fa1fdcffc678cd94)
* [bumped chart version to 0.0.3](https://github.com/observIQ/charts/commit/99dff9d1dc9b3607252980028bcf26779f9f60d8)
Updated the chart to point to the `aerospike-benchmark` image that's built with CI.
> Update Aerospike load generator image

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
* [Added exporter port to service, added label to allow ServiceMonitor to target the service](https://github.com/observIQ/charts/commit/85d1ae23b4b09996278262f27633af0f094d9ef5) 
* [bumped chart version to 0.0.10](https://github.com/observIQ/charts/commit/4618ee134597b91017aac68a0d77c49253786e7e)
For the `ServiceMonitor` resource to target the Apache Cassandra service correctly, a label has to be applied. We also will need the port for the exporter to be included in the service.
> Cassandra: Update service

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
* [updated tag and fixed typo in jmx configuration](https://github.com/observIQ/charts/commit/12ca757161d45d64ac87ab17766207617c1f4b7f)
After updating the tag from `0.0.9` -> `0.0.10` I saw some things revert after running `tk tool charts vendor` to pull the latest changes into the `cloud-onboarding` repo. I'm not 100% sure this will fix it, but I think it's worth a shot, my thought is that it might be equating `0.0.1` to `0.0.10` somehow and that `0.1.0` would be an easy way to solve the issue.
> Cassandra: Fix deployment

- charts/aerospike/Chart.yaml
- charts/aerospike/templates/configmaps.yaml
- charts/aerospike/templates/loadgen.yaml
* [updated namespace in aerospike access address and mesh seed address](https://github.com/observIQ/charts/commit/999eb27f9507f62e67530bcdcd17b1f750f7ae5e)
* [bumped chart version to 0.0.4](https://github.com/observIQ/charts/commit/e1da0d040f5f9b86cbc6f144669cd018327ada8a)
The namespace in the `k3d` environment for sample applications is `sample-apps` and the deployment was failing in the `k3d` environment because the Aerospike configuration has the `default` namespace in the **access-address** and the **mesh-seed-address-port** values. Wanted to make this a value to be configured in `values.yaml` but it didn't seem like that would work.
Had to update the namespace for the loadgen deployment, as well.
> Aerospike: Update namespace for deployments

- charts/aerospike/Chart.yaml
- charts/aerospike/templates/loadgen.yaml
* [updated namespace for the loadgen in the args](https://github.com/observIQ/charts/commit/d3011badcda6487d206f82120636db385d72aa88)
* [bumped chart version to 0.0.5](https://github.com/observIQ/charts/commit/a478de4fbb2093e89dbf628889d111b3bfe9d70d)
The namespace in the in the `args` where the host is specified needs to be updated to `sample-apps` to work in the `k3d` environment. Bumped version to `0.0.5`.
> Aerospike: Update load generation

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
* [added cassandra_cluster label to the service](https://github.com/observIQ/charts/commit/7c90e0b81658d186ff319a01de3fd835b5565d39)
* [bumped chart version to 0.1.1](https://github.com/observIQ/charts/commit/652c738f60ed44bde8c16f767cb357c0929b5ffb)
Added the `cassandra_cluster` label to the service. This is to allow the `ServiceMonitor` resource in the sample-app environment to include the label with the metrics it scrapes and sends to the local Grafana instance.
> Cassandra: Added label `cassandra_cluster` to the service

- charts/aerospike/Chart.yaml
- charts/aerospike/templates/service.yaml
* [added aerospike cluster label to the service to allow serviceMonitor resource to add that label to metrics being scraped](https://github.com/observIQ/charts/commit/06ea214479d197abacdcdde9cfe451c3fac3320a)
* [bumped chart version to 0.0.6](https://github.com/observIQ/charts/pull/71/commits/bf06f8f1cae00591abdc20e845479d58469c06f0)
This change will allow the `ServiceMonitor` resource to target this label and add it to the metrics being scraped by the resource. This is necessary for the work we're doing around the integrations supporting the `k8s` plugin
> Aerospike: Add `aerospike_cluster` label to service

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
* [updated loadgen due to mixed mode not working correctly](https://github.com/observIQ/charts/commit/391a6afe72f5f2f92b5f878d49e5cea2ee899b5a)
* [bumped chart version to 0.1.2](https://github.com/observIQ/charts/commit/67935eec3580d8f5ec8c02b398709df83aeb25a2)
* [fixed typo with the loadgen command](https://github.com/observIQ/charts/pull/73/commits/1926953b069190874e0f014005054cdee0ba7bb8)
Speculating, but it seems as though changes were made to the load generation on the `cloud-onboarding` side and at some point, I overwrote those changes when pulling in new changes from this chart. I could have opted to go with what was present, but I opted for what was the latest in the chart.
Not entirely sure yet, but it sounds like the `mixed` mode didn't actually work as expected and that's why …
> Cassandra: Loadgen Fix

- .github/workflows/ci.yaml
- .github/workflows/container.yaml
- charts/apache-activemq/Chart.yaml
- charts/apache-activemq/templates/configmap.yaml
- charts/apache-activemq/templates/deployment.yaml
- charts/apache-activemq/templates/service.yaml
- charts/apache-activemq/values.yaml
- container/apache-activemq-loadgen/Dockerfile
- container/apache-activemq-loadgen/go.mod
- container/apache-activemq-loadgen/go.sum
- container/apache-activemq-loadgen/receiver-producer.go
* [created activemq deployment with loadgen](https://github.com/observIQ/charts/commit/3958c05c2e8acd06489f33af0529e845ac2e066f)
* [created dockerfile to build activemq loadgen container](https://github.com/observIQ/charts/commit/c16ee7d887e0ada2532988b14bb72e4f8d8b663c)
* [updated deployment to pull loadgen image from values yaml](https://github.com/observIQ/charts/commit/23295967fbf0e81f7e424dd7eac7010b76f7e655)
> There will be a follow up PR to update the image being pulled by the cronJob for load generation, as the image needs to be built by CI before we can include it here.
These changes aim to include a new chart for Apache ActiveMQ with load generation to be used as a sample application in the `grafana/cloud-onboarding` repository.
The deployment is a single instance of ActiveMQ …
> New chart: Apache ActiveMQ

- charts/apache-activemq/templates/service.yaml
* [added activemq_cluster label and fixed typo for metrics port](https://github.com/observIQ/charts/commit/587d488dba31d502a94a0454b2e716da23f3d88f)
The port for the exporter was incorrect and I am adding a label `activemq_cluster` for the sample application in the `cloud-onboarding` repository.
> ActiveMQ: Fix typo and add label to service

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/configmap.yaml
- container/cassandra/config.yaml
* [updated cassandra jmx exporter config and bumped chart version](https://github.com/observIQ/charts/commit/f2f5ce8c3e79046644cc1fdbc2182224f876507c)
* [Applied config changes to container config for future use](https://github.com/observIQ/charts/commit/8731d12056e5c2992cf71e6397f9c6ff84cb6e93)
Updated the JMX exporter config to correctly parse/export the `jvm_gc_collection_count` metric.
> Cassandra: Fix JVM Garbage Collection Count metric

- charts/cassandra/Chart.yaml
- charts/cassandra/templates/deployment.yaml
- charts/cassandra/templates/service.yaml
* [moved cassandra_cluster label to pod spec, bumped chart version](https://github.com/observIQ/charts/commit/11160e3a3035c3079c3f93d77d1db559eded3df1)
This change is required for the sample application logs to be able to also get this label added to them. Originally it was on the `service` definition because the `ServiceMonitor` can target either a label on the service, or labels on the pods, to include those with metrics. The `PodLogs` resource can only utilize the `podTargetLabels` option, meaning that to use this label we either duplicate it, or move it. I've opted to move it, considering the `ServiceMonitor` resource can also utilize the `podTargetLabels` option.
> Cassandra: Move `cassandra_cluster` label to pod spec

- charts/apache-activemq/Chart.yaml
- charts/apache-activemq/templates/configmap.yaml
- charts/apache-activemq/templates/deployment.yaml
- charts/apache-activemq/templates/service.yaml
* [updated jmx config to collect garbage collection metrics](https://github.com/observIQ/charts/commit/7f92a258bbc586fadb99cdc936237a4368505bef)
* [moved activemq cluster label to the pod spec](https://github.com/observIQ/charts/commit/c76d8ed0ab6f91d719ef6d9e0e5b3259bd359956)
* [bumped chart version to 0.0.5](https://github.com/observIQ/charts/commit/b29e2a4eb1f83cb834311a297cfef0120767c3fa)
* [removed whitelistObjectNames to allow gc metrics through](https://github.com/observIQ/charts/commit/7d7a5effd517ef21518716a12c54cd81e2855113)
These changes are necessary for the sample application in the `cloud-onboarding` repo to support using the k8s plugin resources to collect metrics and logs. Previously the JMX configuration did not provide JVM Garbage Collection metrics, so that has also …
> ActiveMQ: Changes for k8s plugin support

- container/apache-activemq-loadgen/receiver-producer.go
* [updated loadgen to use two topics and queues](https://github.com/observIQ/charts/commit/9af5a3edcaa070f619d6761001531ed6a9906cf4)
Updated the load generation to include two queues/topics.
> ActiveMQ: Add second topic/queue to loadgen

- charts/aerospike/Chart.yaml
- charts/aerospike/templates/service.yaml
- charts/aerospike/templates/statefulset.yaml
* [moved aerospike_cluster label to pod spec](https://github.com/observIQ/charts/commit/080be40e6d684ebb2e0a2dbe1a1ff720ffe4aab5)
* [bumped chart version to 0.0.7](https://github.com/observIQ/charts/commit/40e476f44b201feaf8b850cb3b84a46eb61c5c1e)
Moved a label to the pod spec to make targeting the label possible for both the `ServiceMonitor` and `PodLogs` resources that scrape metrics/logs in the k3d environment.
> Aerospike: k8s plugin support

- charts/aerospike/Chart.yaml
- charts/apache-activemq/Chart.yaml
- charts/apache-hadoop/Chart.yaml
- charts/apache-mesos/Chart.yaml
- charts/cassandra/Chart.yaml
- charts/couchbase-community/Chart.yaml
- charts/mssql/Chart.yaml
- charts/oracledbxe/Chart.yaml
- charts/squid/Chart.yaml
- charts/tensorflow/Chart.yaml
- charts/varnish/Chart.yaml
- charts/wildfly/Chart.yaml
* [bumped all chart versions where appropriate to fix failing release](https://github.com/observIQ/application-helm-charts/commit/ac68ba13844c4ea134d140fa9f35f867a02c288b)
The release are failing, I believe this was due to a mistake in not bumping chart versions in #87 so we're bumping them with this PR to hopefully address the failure.
Error Message from failure:
```
Releasing charts...
Error: error creating GitHub release aerospike-0.0.7: POST https://api.github.com/repos/observIQ/application-helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
> Releases: Bumped chart versions to address release failure

- charts/clickhouse/Chart.yaml
- charts/discourse/Chart.yaml
* [Bumped chart versions for Discourse and Clickhouse](https://github.com/observIQ/application-helm-charts/commit/ba850196f3683af827cecd34391370e04a3fa38f)
I believed that these two didn't need to be bumped due to the fact that no changes to these were included in #87 but the release is still failing, and now it happens to be failing on those charts.
Error:
```
Error: error creating GitHub release discourse-9.0.11: POST https://api.github.com/repos/observIQ/application-helm-charts/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
```
> Bump chart versions for Discourse and Clickhouse

- container/prestodb-loadgen/Dockerfile
- container/prestodb-loadgen/prestodb-tpch.sql
* [Added Dockerfile to create loadgen container for PrestoDB](https://github.com/observIQ/charts/commit/0065281f426c98a9e935edaa1a668487666b6370)
This Dockerfile here is simple, it starts from an existing container that has the `prestodb-cli` tool installed. We simply are including a SQL script that targets the TPCH connector/schemas. This TPCH schema generates data on the fly when being queried against, so it's useful here, as we don't really want to setup an entire separate backend storage solution to run queries against through PrestoDB.
> Containers: Add PrestoDB load generation

- .github/workflows/container.yaml
* [added prestodb-loadgen to container release workflow](https://github.com/observIQ/charts/commit/cd93bc50e499965b46d6a6289cc8d7eb69f7678e)
Forgot to update the container workflow in #94 and this should resolve that and release the container.
> Container Workflow: Add PrestoDB Loadgen

- charts/presto/Chart.yaml
- charts/presto/templates/configmap-jmx.yaml
* [Updated the jmx exporter configuration for Presto metrics](https://github.com/observIQ/application-helm-charts/commit/a6b7bd080636b94d6613bcaa52bdb5d23ff785ba)
* [bumped chart version to 1.0.4](https://github.com/observIQ/application-helm-charts/commit/f0c8ea48785cf9466bab8ba1b903d5ec12de521b)
* [updated the jmx exporter configuration to include jvm metrics](https://github.com/observIQ/application-helm-charts/pull/103/commits/c4e0ec3f65a86adf54d8260cc922b61499c1fbfc)
This is a change to update the JMX exporter configuration for Presto so that the metrics are formatted how we'd like them to be.
> Presto: Update JMX exporter configuration

- charts/presto/Chart.yaml
- charts/presto/templates/configmap-jmx.yaml
* [removed lowercase options from the jmx exporter config](https://github.com/observIQ/application-helm-charts/commit/310e4e372c2e68dba74c2f38206288ec0d005d98)
* [bumped chart version to 1.0.5](https://github.com/observIQ/application-helm-charts/commit/1b83d639d8a0d7ddefe26850e80adba7df8a295f)
Including these options breaks the charts within the sample application, so they have been removed.
> Presto: Remove lowercase jmx configuration options

- .github/workflows/container.yaml
- container/influxdb-loadgen/Dockerfile
- container/influxdb-loadgen/loadgen.sh
* [created loadgen container for influxdb](https://github.com/observIQ/application-helm-charts/commit/a9f55974e4e64343e7734426b29b30d3672de879)
Created a container to apply load to InfluxDB
* creates a config for auth
* creates buckets to store data
* writes data from sample files to buckets
* queries the buckets for 5m
* deletes the buckets
> InfluxDB: Load generation container

- charts/influxdb/Chart.yaml
- charts/influxdb/templates/cronjob-loadgen.yaml
- charts/influxdb/values.yaml
* [updated loadgen cronjob to use image released by ci](https://github.com/observIQ/application-helm-charts/commit/6943ff61f74f1727afc5fc54f050189be8a89dfd)
* [bumped chart version to 1.0.1](https://github.com/observIQ/application-helm-charts/commit/2fdbe9664b2217df14b344a0febd2f443acfbba4)
Bumped the chart to a new version. Updated the load generation cronjob resource to pull the image from the `values.yaml` file. Specified the image that was built by CI to be used.
> InfluxDB: Add loadgen to chart

- charts/influxdb/Chart.yaml
- charts/influxdb/values.yaml
* [use new loadgen image for influxdb](https://github.com/observIQ/application-helm-charts/commit/8b9da5fa95c11f31f09f750b9b436250e31fead0)
* [bumped chart version to 1.0.2](https://github.com/observIQ/application-helm-charts/commit/b7d4547a8b9568fc74f5bfb938a15b1dfad61668)
Due to the changes to the load generation container, we're updating the chart to use this new version of that image.
> fix: point to new load generation image

- mq-metric-samples/Dockerfile
- mq-metric-samples/genericresources/createcerts/entrypoint.sh
* [updated dockerfile and created entrypoint script](https://github.com/observIQ/application-helm-charts/commit/780ef1450503cce748111b7ebcbba6cd46dc7cd8)
Updated `create-keystore.sh` to be an entrypoint script that runs at runtime instead of build time. This should create the keystore and import the appropriate certificate, then start the exporter.
> MQ Exporter: Added entrypoint script and updated Dockerfile

- .github/workflows/container-build-test/apache-mesos.yaml
- container/apache-mesos/Dockerfile
This PR adds a change to the Apache Mesos Dockerfile to output `ARCH` to `stdout` and introduces a build test workflow for the Apache Mesos container that, in theory, should run without pushing what gets built.
> Mesos build test workflow
