.github/workflows/ci.yaml, README.md, charts/oracledbxe/Chart.yaml, charts/oracledbxe/templates/deployment.yaml, charts/oracledbxe/values.yaml
* added chart for OracleDB Express Edition 21c
* added deployment for OracleDB Express Edition 21c
=> Add OracleDB XE chart

charts/wildfly/Chart.yaml, charts/wildfly/values.yaml
* Updated the wildfly chart to use newest image, which updates the bind addresses to accept connections from all
=> Updated wildfly chart to use new image

charts/mssql/Chart.yaml, charts/mssql/templates/service.yaml
* Adds a service to the mssql chart exposing port 1433 on the deployment
=> Update MSSQL chart to contain a Service

charts/cassandra/Chart.yaml, charts/cassandra/templates/deployment.yaml, charts/cassandra/values.yaml, container/cassandra/Dockerfile, container/cassandra/docker-compose.yaml
* Added Cassandra container w/ no authentication for remote JMX
* Added chart to create a Cassandra cluster using a StatefulSet and Service
=> Added Cassandra chart and container

.github/workflows/ci.yaml, .github/workflows/container.yaml
* updated ci and container workflows to include cassandra
=> Added Cassandra to CI and Container workflows

charts/cassandra/values.yaml
* updated image being used in chart template to be the container released in the repo
=> Updated Cassandra image in `values.yaml`

charts/cassandra/Chart.yaml
=> Update cassandra chart version

charts/cassandra/Chart.yaml, charts/cassandra/templates/deployment.yaml
* updated the service to expose port 9000 to allow us to scrape metrics from the exporter.
=> Updated Cassandra Service to expose exporter

container/cassandra/Dockerfile, container/cassandra/ready-probe.sh
* Added a readiness probe and script to help with Cassandra startup.
=> Cassandra: Container readiness probe script

charts/cassandra/Chart.yaml, charts/cassandra/templates/deployment.yaml
* updated the `CASSANDRA_SEEDS` value to work w/ the `cloud-onboarding` repo.
=> Cassandra: Deployment changes

charts/apache-mesos/templates/configmap.yaml, charts/apache-mesos/values.yaml, container/apache-mesos/Dockerfile
* Updated Dockerfile instructions to install mesos using community binaries in favor of building from source
* improves build time
* Updated startup script, had to include another flag to disable using systemd by default
=> Updated Apache Mesos Dockerfile instructions

charts/apache-mesos/Chart.yaml
=> Bumped chart version for Apache Mesos

charts/apache-mesos/Chart.yaml, charts/apache-mesos/values.yaml
* updated the image being used to point to the one built by CI
* bumped chart version
=> Updated Apache Mesos chart to use container built with CI

charts/apache-mesos/Chart.yaml, charts/apache-mesos/templates/deployment.yaml
* updated deployment to make the startup script executable
=> Fix for Mesos startup script permissions

.github/workflows/ci.yaml, .github/workflows/container.yaml
* added couchbase to the ci and container workflows
=> Updated workflows to include Couchbase

charts/couchbase-community/Chart.yaml, charts/couchbase-community/README.md
**Changes**
* [updated commands to include namespace flag, added a note](https://github.com/observIQ/charts/commit/9b89e4eff106c9bf622268664a389521127c568c)
* [bumped chart version](https://github.com/observIQ/charts/commit/dc08862135f76fb09bb3213cd895a7b0d8a9aca2)
=> Update Couchbase instructions

docs/MAINTAINERS.md
=> fix: Update MAINTAINERS.md with correct GitHub username

docs/MAINTAINERS.md
=> Fix jsirianni username

docs/MAINTAINERS.md
=> fix: Update MAINTAINERS.md to fix email addresses

container/apache-activemq-loadgen/receiver-producer.go
* [removed duplicated functions in favor of including an argument for the destination](https://github.com/observIQ/charts/commit/fb58d656c8800b1230f9fe271c92fc6738cf6ac4) 
This PR is a small refactor to make the ActiveMQ load generator golang file more readable and concise.
=> ActiveMQ Load Generator: Small refactor

charts/apache-activemq/Chart.yaml
* [bumped chart version to 0.0.3](https://github.com/observIQ/charts/commit/9f0335b5b59be8508a9efe9a45057b0b6aee5233)
Forgot to bump the chart version in this [PR](https://github.com/observIQ/charts/pull/77)
=> ActiveMQ: Bump chart version to 0.0.3

charts/apache-activemq/Chart.yaml, charts/apache-activemq/templates/deployment.yaml, charts/apache-activemq/values.yaml
* [added loadGeneratorNamespace to values for easier use](https://github.com/observIQ/charts/commit/dc9a803d68c1eb30aa3f637bac118da905744cda)
This will allow us to change the namespace to `sample-apps` for the `cloud-onboarding` repository, otherwise it is forced into the `default` namespace, which isn't where sample applications are deployed.
=> ActiveMQ: Added `loadGeneratorNamespace` to `values.yaml`

charts/apache-activemq/Chart.yaml, charts/apache-activemq/values.yaml
* [updated image being used for loadgen, bumped chart version to 0.0.6](https://github.com/observIQ/charts/commit/124bf9af2b4192d95459321f92fae1c0dec0e462)
This change updates the chart to use the updated load generation with multiple queues and topics.
=> ActiveMQ: Use new loadgen container

charts/aerospike/Chart.yaml, charts/apache-activemq/Chart.yaml, charts/apache-hadoop/Chart.yaml, charts/apache-mesos/Chart.yaml, charts/cassandra/Chart.yaml, charts/couchbase-community/Chart.yaml, charts/discourse/Chart.yaml, charts/mssql/Chart.yaml, charts/oracledbxe/Chart.yaml, charts/squid/Chart.yaml, charts/tensorflow/Chart.yaml, charts/varnish/Chart.yaml, charts/wildfly/Chart.yaml
* [updated the links in each Chart yaml file](https://github.com/observIQ/application-helm-charts/commit/b6b09400efb05984979a68a7ac7f25a0944d99a0)
With the change to the name of the repository, we will want to update links where appropriate, to reduce the risk of this not working in the future with the `cloud-onboarding` repo.
=> Update repo links in each `Chart.yaml` file

charts/apache-activemq/Chart.yaml, charts/apache-activemq/templates/configmap.yaml
* [updated valueFactor for jvm_gc_duration_seconds](https://github.com/observIQ/application-helm-charts/commit/f41a1907106c49e89b87b91f7d331d01c8b0a7af)
* [bumped chart version to 0.0.7](https://github.com/observIQ/application-helm-charts/commit/0842c8291120ce7a4a32e4abad2490d426af2f7b)
Initially this value was incorrect and needed to be updated.
=> ActiveMQ: Update `valueFactor` for `jvm_gc_duration_seconds` metric

charts/cassandra/Chart.yaml, charts/cassandra/templates/deployment.yaml
When trying to deploy this resource, it did not like that we had a colon in the value for the label, opted for a hyphen instead.
=> Apache Cassandra: Fix `cluster_label` value

charts/prestodb/Chart.yaml, charts/prestodb/values.yaml
Noticed a copy/paste mistake here and need to get that updated.
=> PrestoDB Chart: Fixed typo for `loadgenImage`

README.md, charts/aerospike/Chart.yaml, charts/apache-activemq/Chart.yaml, charts/apache-hadoop/Chart.yaml, charts/apache-mesos/Chart.yaml, charts/cassandra/Chart.yaml, charts/clickhouse/Chart.yaml, charts/couchbase-community/Chart.yaml, charts/discourse/Chart.yaml, charts/mssql/Chart.yaml, charts/oracledbxe/Chart.yaml, charts/squid/Chart.yaml, charts/tensorflow/Chart.yaml, charts/varnish/Chart.yaml, charts/wildfly/Chart.yaml
=>  chore(rename): Update main branch with new repo name

container/aerospike-benchmark/Dockerfile
I noticed the build process was failing, so I re-factored the Dockerfile. The final image is 18mb.
- Rewrote the dockerfile to use two stage build process
- Use multiple `RUN` instead of single run, clearer.
- Download the same version every time, using curl instead of git
- Use Alpine Golang image for build process, to avoid installing Go
=> fix(container): Re-write aerospike benchmark dockerfile to use two stage build process

container/influxdb-loadgen/loadgen.sh
* [Removed bird migration data and changed which bucket the earthquake data is written to](https://github.com/observIQ/application-helm-charts/commit/7e6dbdc74704b1f30c94621078f3f661683eea37) 
The bird migration data appeared to create error logs in the sample application due to some wackiness with the sample data's timestamps. I'm not quite sure what the deal was, but removing the command to write the bird migration data appears to have resolved the issue.
=> fix: updated influxdb loadgen script

.gitmodules
Added [this repository](https://github.com/ibm-messaging/mq-metric-samples) as a submodule to build the IBM MQ exporter
=> Submodule: IBM MQ Exporter

.github/workflows/mq-exporter-build.yaml
This is a basic workflow to build and release the container image for the IBM MQ exporter
Was not certain what to do with the `on:` section. I don't know if QEMU and building for `arm` will work. Unsure if getting the tag from the environment will work with the submodule.
=> workflow: release IBM MQ exporter container

mq-metric-samples/Dockerfile
* [updated dockerfile to use absolute path to runmqakm utility](https://github.com/observIQ/application-helm-charts/commit/2aa77813e7e78ee201b22b2cb54a0f16ccd7b283)
=> MQ Exporter: use absolute path for `runmqakm` utility

mq-metric-samples/Dockerfile
* [removed instruction that was running the entrypoint script prior to the entrypoint](https://github.com/observIQ/application-helm-charts/commit/c1ce9333d80b4102796f79a64f059f274be62f18)
=> MQ Exporter: Dockerfile fix

charts/couchbase-community/Chart.yaml, charts/couchbase-community/templates/deployment.yaml
Adds a sidecar that operates as a log forwarder for Couchbase logs. It outputs the logs from Couchbase to the STDOUT of the sidecar container. 
* [bumped chart version](https://github.com/observIQ/application-helm-charts/commit/c0fdccc4439aaedde7dea27aac8882d1d82eafb5)
* [added log forwarder sidecar to couchbase statefulset](https://github.com/observIQ/application-helm-charts/commit/5a3b65d315c2714ed226f940d216f5b5e7afc3a1)
=> Couchbase: Add log forwarder

charts/apache-mesos/templates/configmap.yaml, charts/apache-mesos/templates/deployment.yaml
Updated the deployment to include a second container that would run the agent, so as to make my life easier collecting logs from them. ~~Also, updated the startup script to redirect the 'Hit CTRL+C' message to `/dev/null` so that it doesn't show up in the contaier's stdout.~~ Updated the startup scripts to not send everything to the background, then it doesn't complete, so there's no need for the `while` loop.
=> Added separate containers for Mesos master and agent

charts/apache-mesos/Chart.yaml
I forgot to include this change in the previous [PR](https://github.com/observIQ/application-helm-charts/pull/120). Apologies.
=> Updated the mesos chart version

charts/varnish/Chart.yaml, charts/varnish/README.md, charts/varnish/templates/configmaps.yaml, charts/varnish/templates/deployment.yaml, charts/varnish/templates/service-account.yaml, charts/varnish/templates/service.yaml, charts/varnish/values.yaml
This PR adds YAML generated from the official Varnish helm chart, updated to include the exporter for metrics.
=> Update Varnish to use official helm chart

container/apache-mesos/Dockerfile
This PR updates the Dockerfile for the Apache Mesos container so that the version of the downloaded exporter matches the architecture of the build system.
=> fix: add conditional for exporter download based on architecture

.github/workflows/container.yaml
This PR adds the DockerHub login action to use a paid account, which should increase our rate limit, avoiding the error.
=> fix: container pull rate limit error

.github/workflows/container.yaml
Sets `push: true` for the mesos image build job.
=> fix: set push to true for mesos images

charts/apache-mesos/Chart.yaml, charts/apache-mesos/values.yaml
Updates the value being passed to point to the latest build for the Apache Mesos container.
=> fix: mesos image

charts/varnish/Chart.yaml, charts/varnish/templates/configmaps.yaml, charts/varnish/templates/deployment.yaml, charts/varnish/templates/service.yaml
After porting things over to the YAML generated from the official Helm chart, we have added more sidecars for handling logs in the sample application.
* Two ncsa sidecars for frontend/backend logging
* One alloy sidecar to read/ship logs
* Configmap for alloy configuration
Here's a screenshot of the dashboard working in the `k3d` dev cluster
=> feat: Varnish NCSA frontend/backend logs
